### ISSUE TITLE
error while installing electron-prebuilt

### ISSUE THREAD

**Issue by anujk117** [christiannwamba/scotch-player#3]
npm install

> electron-prebuilt@0.36.12 postinstall /home/anuj/Desktop/scotch-player-master/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.36.12-linux-x64.zip
Error: getaddrinfo ENOTFOUND github.com github.com:443
/home/anuj/Desktop/scotch-player-master/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
scotch-player@1.0.0 /home/anuj/Desktop/scotch-player-master
+-- axios@0.9.1 
| `-- follow-redirects@0.0.7 
|   +-- debug@2.6.6 
|   | `-- ms@0.7.3 
|   `-- stream-consume@0.1.0 
+-- babel-preset-es2015@6.24.1 
| +-- babel-plugin-check-es2015-constants@6.22.0 
| | `-- babel-runtime@6.23.0 
| |   +-- core-js@2.4.1 
| |   `-- regenerator-runtime@0.10.5 
| +-- babel-plugin-transform-es2015-arrow-functions@6.22.0 
| +-- babel-plugin-transform-es2015-block-scoped-functions@6.22.0 
| +-- babel-plugin-transform-es2015-block-scoping@6.24.1 
| | +-- babel-template@6.24.1 
| | +-- babel-traverse@6.24.1 
| | | +-- globals@9.17.0 
| | | `-- invariant@2.2.2 
| | +-- babel-types@6.24.1 
| | | +-- esutils@2.0.2 
| | | `-- to-fast-properties@1.0.3 
| | `-- lodash@4.17.4 
| +-- babel-plugin-transform-es2015-classes@6.24.1 
| | +-- babel-helper-define-map@6.24.1 
| | +-- babel-helper-function-name@6.24.1 
| | +-- babel-helper-optimise-call-expression@6.24.1 
| | +-- babel-helper-replace-supers@6.24.1 
| | `-- babel-messages@6.23.0 
| +-- babel-plugin-transform-es2015-computed-properties@6.24.1 
| +-- babel-plugin-transform-es2015-destructuring@6.23.0 
| +-- babel-plugin-transform-es2015-duplicate-keys@6.24.1 
| +-- babel-plugin-transform-es2015-for-of@6.23.0 
| +-- babel-plugin-transform-es2015-function-name@6.24.1 
| +-- babel-plugin-transform-es2015-literals@6.22.0 
| +-- babel-plugin-transform-es2015-modules-amd@6.24.1 
| +-- babel-plugin-transform-es2015-modules-commonjs@6.24.1 
| | `-- babel-plugin-transform-strict-mode@6.24.1 
| +-- babel-plugin-transform-es2015-modules-systemjs@6.24.1 
| | `-- babel-helper-hoist-variables@6.24.1 
| +-- babel-plugin-transform-es2015-modules-umd@6.24.1 
| +-- babel-plugin-transform-es2015-object-super@6.24.1 
| +-- babel-plugin-transform-es2015-parameters@6.24.1 
| | +-- babel-helper-call-delegate@6.24.1 
| | `-- babel-helper-get-function-arity@6.24.1 
| +-- babel-plugin-transform-es2015-shorthand-properties@6.24.1 
| +-- babel-plugin-transform-es2015-spread@6.22.0 
| +-- babel-plugin-transform-es2015-sticky-regex@6.24.1 
| | `-- babel-helper-regex@6.24.1 
| +-- babel-plugin-transform-es2015-template-literals@6.22.0 
| +-- babel-plugin-transform-es2015-typeof-symbol@6.23.0 
| +-- babel-plugin-transform-es2015-unicode-regex@6.24.1 
| | `-- regexpu-core@2.0.0 
| |   +-- regenerate@1.3.2 
| |   +-- regjsgen@0.2.0 
| |   `-- regjsparser@0.1.5 
| |     `-- jsesc@0.5.0 
| `-- babel-plugin-transform-regenerator@6.24.1 
|   `-- regenerator-transform@0.9.11 
+-- babel-preset-react@6.24.1 
| +-- babel-plugin-syntax-jsx@6.18.0 
| +-- babel-plugin-transform-react-display-name@6.23.0 
| +-- babel-plugin-transform-react-jsx@6.24.1 
| | `-- babel-helper-builder-react-jsx@6.24.1 
| +-- babel-plugin-transform-react-jsx-self@6.22.0 
| +-- babel-plugin-transform-react-jsx-source@6.22.0 
| `-- babel-preset-flow@6.23.0 
|   `-- babel-plugin-transform-flow-strip-types@6.22.0 
|     `-- babel-plugin-syntax-flow@6.18.0 
+-- babelify@7.3.0 
| +-- babel-core@6.24.1 
| | +-- babel-code-frame@6.22.0 
| | | +-- chalk@1.1.3 
| | | | +-- ansi-styles@2.2.1 
| | | | +-- escape-string-regexp@1.0.5 
| | | | +-- has-ansi@2.0.0 
| | | | | `-- ansi-regex@2.1.1 
| | | | +-- strip-ansi@3.0.1 
| | | | `-- supports-color@2.0.0 
| | | `-- js-tokens@3.0.1 
| | +-- babel-generator@6.24.1 
| | | +-- detect-indent@4.0.0 
| | | | `-- repeating@2.0.1 
| | | |   `-- is-finite@1.0.2 
| | | |     `-- number-is-nan@1.0.1 
| | | +-- jsesc@1.3.0 
| | | `-- trim-right@1.0.1 
| | +-- babel-helpers@6.24.1 
| | +-- babel-register@6.24.1 
| | | +-- home-or-tmp@2.0.0 
| | | | +-- os-homedir@1.0.2 
| | | | `-- os-tmpdir@1.0.2 
| | | +-- mkdirp@0.5.1 
| | | | `-- minimist@0.0.8 
| | | `-- source-map-support@0.4.15 
| | +-- babylon@6.17.1 
| | +-- convert-source-map@1.5.0 
| | +-- json5@0.5.1 
| | +-- minimatch@3.0.4 
| | | `-- brace-expansion@1.1.7 
| | |   +-- balanced-match@0.4.2 
| | |   `-- concat-map@0.0.1 
| | +-- path-is-absolute@1.0.1 
| | +-- private@0.1.7 
| | +-- slash@1.0.0 
| | `-- source-map@0.5.6 
| `-- object-assign@4.1.1 
+-- classnames@2.2.5 
+-- electron-reload@0.2.0 
| `-- chokidar@1.7.0 
|   +-- anymatch@1.3.0 
|   | +-- arrify@1.0.1 
|   | `-- micromatch@2.3.11 
|   |   +-- arr-diff@2.0.0 
|   |   | `-- arr-flatten@1.0.3 
|   |   +-- array-unique@0.2.1 
|   |   +-- braces@1.8.5 
|   |   | +-- expand-range@1.8.2 
|   |   | | `-- fill-range@2.2.3 
|   |   | |   +-- is-number@2.1.0 
|   |   | |   +-- isobject@2.1.0 
|   |   | |   | `-- isarray@1.0.0 
|   |   | |   +-- randomatic@1.1.6 
|   |   | |   `-- repeat-string@1.6.1 
|   |   | +-- preserve@0.2.0 
|   |   | `-- repeat-element@1.1.2 
|   |   +-- expand-brackets@0.1.5 
|   |   | `-- is-posix-bracket@0.1.1 
|   |   +-- extglob@0.3.2 
|   |   +-- filename-regex@2.0.1 
|   |   +-- kind-of@3.2.0 
|   |   | `-- is-buffer@1.1.5 
|   |   +-- normalize-path@2.1.1 
|   |   | `-- remove-trailing-separator@1.0.1 
|   |   +-- object.omit@2.0.1 
|   |   | +-- for-own@0.1.5 
|   |   | | `-- for-in@1.0.2 
|   |   | `-- is-extendable@0.1.1 
|   |   +-- parse-glob@3.0.4 
|   |   | +-- glob-base@0.3.0 
|   |   | `-- is-dotfile@1.0.2 
|   |   `-- regex-cache@0.4.3 
|   |     +-- is-equal-shallow@0.1.3 
|   |     `-- is-primitive@2.0.0 
|   +-- async-each@1.0.1 
|   +-- glob-parent@2.0.0 
|   +-- inherits@2.0.3 
|   +-- is-binary-path@1.0.1 
|   | `-- binary-extensions@1.8.0 
|   +-- is-glob@2.0.1 
|   | `-- is-extglob@1.0.0 
|   `-- readdirp@2.1.0 
|     +-- graceful-fs@4.1.11 
|     +-- readable-stream@2.2.9 
|     | +-- buffer-shims@1.0.0 
|     | +-- core-util-is@1.0.2 
|     | +-- isarray@1.0.0 
|     | +-- process-nextick-args@1.0.7 
|     | +-- string_decoder@1.0.0 
|     | `-- util-deprecate@1.0.2 
|     `-- set-immediate-shim@1.0.1 
+-- jquery@2.2.4 
+-- react@0.14.9 
| +-- envify@3.4.1 
| | +-- jstransform@11.0.3 
| | | +-- base62@1.1.2 
| | | +-- commoner@0.10.8 
| | | | +-- commander@2.9.0 
| | | | | `-- graceful-readlink@1.0.1 
| | | | +-- detective@4.5.0 
| | | | | +-- acorn@4.0.11 
| | | | | `-- defined@1.0.0 
| | | | +-- glob@5.0.15 
| | | | | +-- inflight@1.0.6 
| | | | | | `-- wrappy@1.0.2 
| | | | | `-- once@1.4.0 
| | | | +-- iconv-lite@0.4.17 
| | | | +-- q@1.5.0 
| | | | `-- recast@0.11.23 
| | | |   +-- ast-types@0.9.6 
| | | |   `-- esprima@3.1.3 
| | | +-- esprima-fb@15001.1.0-dev-harmony-fb 
| | | +-- object-assign@2.1.1 
| | | `-- source-map@0.4.4 
| | |   `-- amdefine@1.0.1 
| | `-- through@2.3.8 
| `-- fbjs@0.6.1 
|   +-- core-js@1.2.7 
|   +-- loose-envify@1.3.1 
|   +-- promise@7.1.1 
|   | `-- asap@2.0.5 
|   +-- ua-parser-js@0.7.12 
|   `-- whatwg-fetch@0.9.0 
+-- react-autocomplete@1.5.2 
| `-- dom-scroll-into-view@1.0.1 
+-- react-dom@0.14.9 
+-- react-sound@0.4.0 
`-- soundmanager2@2.97.20150601-a 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.12 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.36.12 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anuj/Desktop/scotch-player-master/npm-debug.log

**Comment by anujk117** [comment]
no error when installed on another system. So Reinstalled my os , working.
